[2018-08-16 11:24:49,985]-result.py:34-ERROR - AdPicUploadHandler error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/admin/common/result.py", line 29, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/admin/handlers/user.py", line 109, in _get
    pics = self.get_pics()
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/admin/handlers/user.py", line 93, in get_pics
    n, _ = f.split('_')
ValueError: too many values to unpack

[2018-08-16 11:46:09,443]-result.py:57-ERROR - GoodsList error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 54, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 100, in _get
    return self.render_html('app/goods_list.html',goods_list=goods_list*4, pics=pics)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 130, in render_html
    return self.render(template_name, **kwargs)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 125, in render
    self.finish(self._render_string(template_name, **kwargs))
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 121, in _render_string
    return template.render_unicode(**kwargs).encode('utf-8','replace')
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/template.py", line 471, in render_unicode
    as_unicode=True)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "app_goods_list_html", line 36, in render_body
TypeError: an integer is required

[2018-08-16 14:53:06,474]-result.py:57-ERROR - BuyGoods error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 52, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 180, in _get
    address_id = int(self.get_argument('address_id', self.user.deliver_address_id))
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/utils/extend.py", line 25, in __getattr__
    raise AttributeError, k
AttributeError: 'deliver_address_id'

[2018-08-16 14:53:17,179]-result.py:57-ERROR - BuyGoods error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 52, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 180, in _get
    address_id = int(self.get_argument('address_id', self.user.deliver_address_id))
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/utils/extend.py", line 25, in __getattr__
    raise AttributeError, k
AttributeError: 'deliver_address_id'

[2018-08-16 14:53:23,323]-result.py:57-ERROR - BuyGoods error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 52, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 180, in _get
    address_id = int(self.get_argument('address_id', self.user.deliver_address_id))
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/utils/extend.py", line 25, in __getattr__
    raise AttributeError, k
AttributeError: 'deliver_address_id'

[2018-08-16 14:53:42,816]-result.py:57-ERROR - PersonalInfo error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 52, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/user.py", line 128, in _get
    info['nickname'] = user.nickname
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/utils/extend.py", line 25, in __getattr__
    raise AttributeError, k
AttributeError: 'nickname'

[2018-08-16 16:22:56,621]-result.py:57-ERROR - OrderList error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 52, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/user.py", line 385, in _get
    return self.render_html('app/order_list.html',order_list=order_list)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 130, in render_html
    return self.render(template_name, **kwargs)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 125, in render
    self.finish(self._render_string(template_name, **kwargs))
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 121, in _render_string
    return template.render_unicode(**kwargs).encode('utf-8','replace')
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/template.py", line 471, in render_unicode
    as_unicode=True)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "app_order_list_html", line 32, in render_body
KeyError: 'brief'

[2018-08-16 16:45:55,907]-result.py:57-ERROR - GoodsList error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 54, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 100, in _get
    return self.render_html('app/goods_list.html',goods_list=goods_list*4, pics=pics)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 130, in render_html
    return self.render(template_name, **kwargs)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 125, in render
    self.finish(self._render_string(template_name, **kwargs))
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 121, in _render_string
    return template.render_unicode(**kwargs).encode('utf-8','replace')
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/template.py", line 471, in render_unicode
    as_unicode=True)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "app_goods_list_html", line 58, in render_body
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 226, in __str__
    raise NameError("Undefined")
NameError: Undefined

[2018-08-16 17:00:45,280]-result.py:57-ERROR - GoodsList error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 54, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 100, in _get
    pics = self.get_pics()
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 130, in render_html
    return self.render(template_name, **kwargs)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 125, in render
    self.finish(self._render_string(template_name, **kwargs))
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 121, in _render_string
    return template.render_unicode(**kwargs).encode('utf-8','replace')
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/template.py", line 471, in render_unicode
    as_unicode=True)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "app_goods_list_html", line 58, in render_body
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 226, in __str__
    raise NameError("Undefined")
NameError: Undefined

[2018-08-16 17:00:53,192]-result.py:57-ERROR - GoodsList error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 54, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 100, in _get
    pics = self.get_pics()
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 130, in render_html
    return self.render(template_name, **kwargs)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 125, in render
    self.finish(self._render_string(template_name, **kwargs))
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 121, in _render_string
    return template.render_unicode(**kwargs).encode('utf-8','replace')
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/template.py", line 471, in render_unicode
    as_unicode=True)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "app_goods_list_html", line 58, in render_body
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 226, in __str__
    raise NameError("Undefined")
NameError: Undefined

[2018-08-16 17:12:59,659]-result.py:57-ERROR - GoodsDetail error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 54, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 109, in _get
    goods_id = int(self.get_argument('goods_id', 0))
ValueError: invalid literal for int() with base 10: '1/favicon.ico'

[2018-08-16 18:14:51,691]-result.py:57-ERROR - GoodsDetail error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 54, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 109, in _get
    goods_id = int(self.get_argument('goods_id', 0))
ValueError: invalid literal for int() with base 10: '1/favicon.ico'

[2018-08-16 18:15:01,980]-result.py:57-ERROR - GoodsDetail error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 54, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/goods.py", line 109, in _get
    goods_id = int(self.get_argument('goods_id', 0))
ValueError: invalid literal for int() with base 10: '1/favicon.ico'

[2018-08-16 18:31:19,097]-result.py:57-ERROR - PersonalInfo error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 52, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/user.py", line 128, in _get
    info['nickname'] = user.nickname
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/utils/extend.py", line 25, in __getattr__
    raise AttributeError, k
AttributeError: 'nickname'

