[2018-08-23 17:27:56,925]-result.py:57-ERROR - OrderList error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 52, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/user.py", line 385, in _get
    return self.render_html('app/order_list.html')
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 130, in render_html
    return self.render(template_name, **kwargs)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 125, in render
    self.finish(self._render_string(template_name, **kwargs))
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 121, in _render_string
    return template.render_unicode(**kwargs).encode('utf-8','replace')
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/template.py", line 471, in render_unicode
    as_unicode=True)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "app_order_list_html", line 22, in render_body
TypeError: 'Undefined' object is not iterable

[2018-08-23 17:31:09,069]-result.py:57-ERROR - OrderList error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 52, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/user.py", line 385, in _get
    return self.render_html('app/order_list.html')
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 130, in render_html
    return self.render(template_name, **kwargs)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 125, in render
    self.finish(self._render_string(template_name, **kwargs))
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 121, in _render_string
    return template.render_unicode(**kwargs).encode('utf-8','replace')
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/template.py", line 471, in render_unicode
    as_unicode=True)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "app_order_list_html", line 22, in render_body
TypeError: 'Undefined' object is not iterable

[2018-08-23 17:35:06,303]-result.py:57-ERROR - OrderList error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 52, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/user.py", line 385, in _get
    return self.render_html('app/order_list.html')
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 130, in render_html
    return self.render(template_name, **kwargs)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 125, in render
    self.finish(self._render_string(template_name, **kwargs))
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 121, in _render_string
    return template.render_unicode(**kwargs).encode('utf-8','replace')
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/template.py", line 471, in render_unicode
    as_unicode=True)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "app_order_list_html", line 22, in render_body
TypeError: 'Undefined' object is not iterable

[2018-08-23 17:36:38,926]-result.py:57-ERROR - OrderList error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 52, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/user.py", line 385, in _get
    return self.render_html('app/order_list.html')
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 130, in render_html
    return self.render(template_name, **kwargs)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 125, in render
    self.finish(self._render_string(template_name, **kwargs))
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 121, in _render_string
    return template.render_unicode(**kwargs).encode('utf-8','replace')
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/template.py", line 471, in render_unicode
    as_unicode=True)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "app_order_list_html", line 22, in render_body
TypeError: 'Undefined' object is not iterable

[2018-08-23 17:37:45,384]-result.py:57-ERROR - OrderList error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 52, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/user.py", line 385, in _get
    return self.render_html('app/order_list.html')
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 130, in render_html
    return self.render(template_name, **kwargs)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 125, in render
    self.finish(self._render_string(template_name, **kwargs))
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 121, in _render_string
    return template.render_unicode(**kwargs).encode('utf-8','replace')
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/template.py", line 471, in render_unicode
    as_unicode=True)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "app_order_list_html", line 22, in render_body
TypeError: 'Undefined' object is not iterable

[2018-08-23 17:37:50,255]-result.py:57-ERROR - OrderList error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 52, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/user.py", line 385, in _get
    return self.render_html('app/order_list.html')
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 130, in render_html
    return self.render(template_name, **kwargs)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 125, in render
    self.finish(self._render_string(template_name, **kwargs))
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 121, in _render_string
    return template.render_unicode(**kwargs).encode('utf-8','replace')
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/template.py", line 471, in render_unicode
    as_unicode=True)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "app_order_list_html", line 22, in render_body
TypeError: 'Undefined' object is not iterable

[2018-08-23 17:39:31,825]-result.py:57-ERROR - OrderList error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 52, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/user.py", line 385, in _get
    return self.render_html('app/order_list.html')
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 130, in render_html
    return self.render(template_name, **kwargs)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 125, in render
    self.finish(self._render_string(template_name, **kwargs))
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 121, in _render_string
    return template.render_unicode(**kwargs).encode('utf-8','replace')
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/template.py", line 471, in render_unicode
    as_unicode=True)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "app_order_list_html", line 22, in render_body
TypeError: 'Undefined' object is not iterable

[2018-08-23 17:40:33,519]-result.py:57-ERROR - OrderList error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 52, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/user.py", line 385, in _get
    return self.render_html('app/order_list.html')
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 130, in render_html
    return self.render(template_name, **kwargs)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 125, in render
    self.finish(self._render_string(template_name, **kwargs))
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 121, in _render_string
    return template.render_unicode(**kwargs).encode('utf-8','replace')
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/template.py", line 471, in render_unicode
    as_unicode=True)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "app_order_list_html", line 22, in render_body
TypeError: 'Undefined' object is not iterable

[2018-08-23 17:45:15,594]-result.py:57-ERROR - OrderList error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 52, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/user.py", line 432, in _post
    return Result(alert.SUCCESS, data=order_list)()
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 74, in __call__
    return self.as_json()
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 77, in as_json
    return escape.json_encode(self.__dict__)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/tornado/escape.py", line 88, in json_encode
    return json.dumps(value).replace("</", "<\\/")
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2018, 8, 20, 17, 1, 52) is not JSON serializable

[2018-08-23 17:45:42,618]-result.py:57-ERROR - OrderList error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 52, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/user.py", line 432, in _post
    return Result(alert.SUCCESS, data=order_list)()
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 74, in __call__
    return self.as_json()
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 77, in as_json
    return escape.json_encode(self.__dict__)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/tornado/escape.py", line 88, in json_encode
    return json.dumps(value).replace("</", "<\\/")
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2018, 8, 20, 17, 1, 52) is not JSON serializable

[2018-08-23 17:45:51,097]-result.py:57-ERROR - OrderList error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 52, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/user.py", line 432, in _post
    return Result(alert.SUCCESS, data=order_list)()
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 74, in __call__
    return self.as_json()
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 77, in as_json
    return escape.json_encode(self.__dict__)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/tornado/escape.py", line 88, in json_encode
    return json.dumps(value).replace("</", "<\\/")
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2018, 8, 20, 17, 1, 52) is not JSON serializable

[2018-08-23 17:45:57,163]-result.py:57-ERROR - OrderList error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 52, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/user.py", line 432, in _post
    return Result(alert.SUCCESS, data=order_list)()
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 74, in __call__
    return self.as_json()
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 77, in as_json
    return escape.json_encode(self.__dict__)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/tornado/escape.py", line 88, in json_encode
    return json.dumps(value).replace("</", "<\\/")
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2018, 8, 20, 17, 1, 52) is not JSON serializable

[2018-08-23 17:46:05,749]-result.py:57-ERROR - OrderList error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 52, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/user.py", line 432, in _post
    return Result(alert.SUCCESS, data=order_list)()
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 74, in __call__
    return self.as_json()
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 77, in as_json
    return escape.json_encode(self.__dict__)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/tornado/escape.py", line 88, in json_encode
    return json.dumps(value).replace("</", "<\\/")
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2018, 8, 20, 17, 1, 52) is not JSON serializable

[2018-08-23 17:55:00,793]-result.py:57-ERROR - OrderList error:Traceback (most recent call last):
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/common/result.py", line 52, in __deco
    return func(self)
  File "/Users/shuai.chen/eclipse-workspace/app-breeding/app/handlers/user.py", line 385, in _get
    return self.render_html('app/order_list.html')
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 130, in render_html
    return self.render(template_name, **kwargs)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 125, in render
    self.finish(self._render_string(template_name, **kwargs))
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/towgo-1.0.0-py2.7.egg/towgo/handler.py", line 121, in _render_string
    return template.render_unicode(**kwargs).encode('utf-8','replace')
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/template.py", line 471, in render_unicode
    as_unicode=True)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/Users/shuai.chen/pyenv/lib/python2.7/site-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "app_order_list_html", line 22, in render_body
TypeError: 'Undefined' object is not iterable

